# Generated by Django 2.1.1 on 2018-09-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_band', models.BooleanField(choices=[['individual', False], ['band', True]], default=False, verbose_name='Individual/Band')),
            ],
        ),
    ]
