# Generated by Django 2.1.1 on 2018-09-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180930_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='is_band',
            field=models.BooleanField(choices=[[False, 'individual'], [True, 'band']], default=False, verbose_name="It's a band"),
        ),
    ]
