# Generated by Django 2.1.1 on 2018-09-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20180930_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='is_band',
            field=models.BooleanField(choices=[[False, 'musician'], [True, 'band']], default=False, verbose_name='Musician/Band'),
        ),
    ]
